
#include "archive_test.cpp"
#include "basichighlighting_test.cpp"
#include "buffer_test.cpp"
#include "bufferkeymap_test.cpp"
#include "cursorops_test.cpp"
#include "cursorrangeops_test.cpp"
#include "fstring_test.cpp"
#include "history_test.cpp"
#include "keysettings_test.cpp"
#include "mode_test.cpp"
#include "palette_test.cpp"
#include "playbackedit_test.cpp"
#include "project_test.cpp"
#include "serializescreen_test.cpp"
#include "utf8char_test.cpp"
#include "wordsiterator_test.cpp"
