#pragma once

class IMode;
class KeyEvent;
class Buffer;
class FChar;
class Position;
class Cursor;
class CursorRange;
class IScreen;
class IView;
class IMode;
class Editor;
class IFile;
class IEnvironment;
class BufferView;
class Command;
class CommandBlock;
class ClangModel;
class IHighlight;
