#include "remote/fifoconnection.cpp"
#include "remote/fifofile.cpp"
#include "remote/tcpconnection.cpp"
#include "remote/tcpserver.cpp"
#include "screen/deserializescreen.cpp"
#include "screen/serializescreen.cpp"
#include "thinmain.cpp"
