name: Test Linux

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  test-build:
    # Name the Job
    name: Test build
    # Set the type of machine to run on
    runs-on: ubuntu-20.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup C++ environment
        uses: kurocha/setup-cpp@v1
      - name: Update recursive
        run: git submodule update --recursive --init
      - name: Build build-system
        run: make -C matmake -j8
      - name: Install tools
        run: |
          pip install cmake==3.18.2.post1 ninja==1.10.0.post1 --upgrade
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-10 main' -y
          sudo apt update
          sudo apt-get install -y clang-10 libclang-9-dev
      - name: Build and test
        run: matmake/matmake -v -c debug test
        
        

