name: Emscripten

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  test-build:
    # Name the Job
    name: Test build
    # Set the type of machine to run on
    runs-on: ubuntu-20.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup C++ environment
        uses: kurocha/setup-cpp@v1
      - name: Update recursive
        run: git submodule update --recursive --init
      - name: Build build-system
        run: make -C matmake2
      - name: Install emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          emsdk/emsdk install latest
          emsdk/emsdk activate latest

      - name: Build emscripten
        run: |
          source emsdk/emsdk_env.sh
          matmake2/build/matmake2 -t em test



